spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/demo?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
      username: root
      password:
      initial-size: 5
      max-active: 20
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters:
            commons-log.connection-logger-name: stat,wall,log4j
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 1 from dual
mybatis:
  mapper-locations: classpath:mapper/*.xml
  property:
    order: BEFORE
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.mybatismapper.demo.entity

pagehelper:
  helper-dialect: MYSQL
  params: count=countSql
  reasonable: false
  support-methods-arguments: true
mapper:
  mappers: tk.mybatis.mapper.common.BaseMapper
  not-empty: false
  identity: MYSQL
