spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/demo?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
      username: root
      password: root
      initial-size: 5
      max-active: 20
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters:
            commons-log.connection-logger-name: stat,wall,log4j
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 1 from dual
  cache:
      ehcache:
        config: 'classpath:ehcache.xml'
      cache-names: user

mybatis:
  # type-aliases扫描路径
  # type-aliases-package:
  # mapper xml实现扫描路径
  mapper-locations: classpath:mapper/*.xml
  property:
    order: BEFORE
  configuration:
#  输出sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl