server:
  port: 8080
  context-path: /admin-server

spring:
  mail:
    host: smtp.163.com
    username:
    password: ÓÊÏäÊÚÈ¨Âë
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  boot:
    admin:
      notify:
        mail:
          enabled: true
          from:
          to: