spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/spdb?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
      username: root
      password: infosys668
      initial-size: 5
      max-active: 20
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters:
            commons-log.connection-logger-name: stat,wall,log4j
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 1 from dual
mybatis:
  # type-aliases扫描路径
  # type-aliases-package:
  # mapper xml实现扫描路径
  mapper-locations: classpath:mapper/*.xml
  property:
    order: BEFORE