spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/demo?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
      username: root
      password:
      initial-size: 5
      max-active: 20
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters:
            commons-log.connection-logger-name: stat,wall,log4j
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 1 from dual
  jpa:
    database: mysql
    show-sql: true
    hibernate:
          naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
          ddl-auto: update