spring:
  datasource:
    druid:
      url: jdbc:mysql://192.168.1.195:3306/demo?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
      username: root
      password: 123456
  jpa:
    database: mysql
    show-sql: true
    hibernate:
          ddl-auto: update